version: "3.8"

services:
    app:
        build:
            context: /home/iqbal
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - /home/iqbal:/var/www
        expose:
            - "9000"
        depends_on:
            - mysql

    nginx:
        image: nginx:stable-alpine
        ports:
            - "8181:80"
        volumes:
            - /home/iqbal:/var/www
            - /home/iqbal/nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel_coolify_db
            MYSQL_USER: laravel_coolify_user
            MYSQL_PASSWORD: laravel_coolify_pass
        volumes:
            - /home/iqbal/mysql_data:/var/lib/mysql
        expose:
            - "3306"

volumes:
    mysql_data:
        driver: local
