version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            APP_ENV: local
            APP_DEBUG: true
            APP_KEY:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - db
        command: php-fpm

    webserver:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: always
        ports:
            - "8300:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
