version: "3.8"

services:
    app:
        image: php:8.3-fpm
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        command: >
            sh -c "
              composer install --optimize-autoloader --no-dev &&
              npm ci && npm run build &&
              php artisan config:cache &&
              php artisan route:cache &&
              php artisan view:cache &&
              php artisan storage:link &&
              chmod -R ug+w storage bootstrap/cache &&
              php-fpm
            "
        ports:
            - "9000:9000"

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./storage:/var/www/storage
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel_coolify_db
            MYSQL_USER: laravel_coolify_user
            MYSQL_PASSWORD: laravel_coolify_pass
        ports:
            - "3306:3306"
